apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-trap-app
  labels:
    app: snmp-trap-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snmp-trap-app
  template:
    metadata:
      labels:
        app: snmp-trap-app
    spec:
      containers:
        - name: snmp-trap-app
          image: charithakula/snmp-trap-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: CREDENTIALS_PATH
              value: "/app/credentials.json"
          volumeMounts:
            - name: config-volume
              mountPath: "/app/credentials.json"
              subPath: "credentials.json"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: snmp-trap-app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-trap-app-config
data:
  credentials.json: |
    {
      "snmpv3_user": "your_user",
      "auth_password": "your_auth_password",
      "priv_password": "your_priv_password",
      "auth_protocol": "SHA",
      "priv_protocol": "AES",
      "snmp_target_ip": "127.0.0.1",
      "snmp_target_port": "162"
    }
