apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-trap-sender
  labels:
    app: snmp-trap-sender
spec:
  replicas: 1  # You can increase this to scale up
  selector:
    matchLabels:
      app: snmp-trap-sender
  template:
    metadata:
      labels:
        app: snmp-trap-sender
    spec:
      containers:
        - name: snmp-trap-sender
          image: your-docker-image:latest  # Replace with your actual Docker image
          ports:
            - containerPort: 8002
          env:
            - name: SNMP_USER
              valueFrom:
                secretKeyRef:
                  name: snmp-credentials
                  key: snmpv3_user
            - name: SNMP_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snmp-credentials
                  key: auth_password
            - name: SNMP_PRIV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snmp-credentials
                  key: priv_password
            - name: SNMP_AUTH_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: snmp-credentials
                  key: auth_protocol
            - name: SNMP_PRIV_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: snmp-credentials
                  key: priv_protocol
          volumeMounts:
            - name: snmp-credentials-volume
              mountPath: /etc/snmp
              readOnly: true
      volumes:
        - name: snmp-credentials-volume
          secret:
            secretName: snmp-credentials  # Define the secret with SNMP credentials
