apiVersion: v1
kind: Secret
metadata:
  name: snmp-credentials
type: Opaque
data:
  snmpv3_user: <base64-encoded-value>
  auth_password: <base64-encoded-value>
  priv_password: <base64-encoded-value>
  auth_protocol: <base64-encoded-value>  # Example: 'SHA' or 'MD5'
  priv_protocol: <base64-encoded-value>  # Example: 'AES' or 'DES'
