apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-app-service
  labels:
    app: snmp-trap-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: snmp-trap-app